FROM mongo

ENV MONGO_INITDB_ROOT_USERNAME=aseAdmin
ENV MONGO_INITDB_ROOT_PASSWORD=ase

# Define default command.
CMD ["mongod"]

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017
EXPOSE 28017